CREATE TABLE TB_GAMES
(
    GAME_ID      INT PRIMARY KEY AUTO_INCREMENT,
    TITLE        VARCHAR(100) NOT NULL,
    VALUE        DECIMAL(10, 2) NOT NULL,
    RELEASE_DATE DATE NOT NULL
);

CREATE TABLE TB_USERS
(
    USER_ID  INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL    VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    ROLE   VARCHAR(100) DEFAULT 'USER' NOT NULL,
    UNIQUE (EMAIL)
);